plugins {
    id 'java'
    id 'war'
}

group = 'com.walking.carpractice'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.18.3'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.1.0'
    testImplementation 'jakarta.servlet:jakarta.servlet-api:6.1.0'

    implementation 'org.mindrot:jbcrypt:0.4'

    runtimeOnly 'org.postgresql:postgresql:42.7.2'
    implementation 'org.hibernate.orm:hibernate-core:6.6.2.Final'
    //implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'

    implementation 'com.zaxxer:HikariCP:5.1.0'

    implementation 'org.flywaydb:flyway-core:10.11.0'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql:10.11.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    testImplementation 'org.mockito:mockito-core:5.10.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.10.0'

    implementation 'org.apache.logging.log4j:log4j-api:2.12.4'
    implementation 'org.apache.logging.log4j:log4j-core:2.12.4'
    implementation 'org.apache.logging.log4j:log4j-slf4j-impl:2.12.4'

    annotationProcessor 'org.hibernate:hibernate-jpamodelgen:6.6.2.Final'
}
war {
    archiveFileName = 'carjpa.war'
}

test {
    useJUnitPlatform()
}

// Для всех тасок, отвечающих за компиляцию Java-кода
tasks.withType(JavaCompile)
        .configureEach {
//    Перенесем вывод (сохранение сгенерированных файлов) в директорию по пути "${projectHome}/src/generated/java"
            options.getGeneratedSourceOutputDirectory().set(file("src/generated/java"))
        }

sourceSets {
// Добавим новый source set - "generated" (ранее существовали лишь "main" и "test")
    generated {
// В этом source set'е будем работать с Java
        java {
// Исходный код для данного source set'а будем складывать в директорию "src/generated/java"
            srcDirs = ['src/generated/java']
        }
    }
}